### ISSUE TITLE
Class org.apache.hadoop.fs.s3a.S3AFileSystem not found

### ISSUE THREAD

**Issue by yohei1126** [CoorpAcademy/docker-pyspark#13]
```
hdfs dfs -ls s3a://xxxxx/
17/12/29 08:58:59 WARN util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
-ls: Fatal internal error
java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2195)
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2638)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2651)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.hadoop.fs.shell.PathData.expandAsGlob(PathData.java:325)
        at org.apache.hadoop.fs.shell.Command.expandArgument(Command.java:235)
        at org.apache.hadoop.fs.shell.Command.expandArguments(Command.java:218)
        at org.apache.hadoop.fs.shell.Command.processRawArguments(Command.java:201)
        at org.apache.hadoop.fs.shell.Command.run(Command.java:165)
        at org.apache.hadoop.fs.FsShell.run(FsShell.java:287)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
        at org.apache.hadoop.fs.FsShell.main(FsShell.java:340)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
        at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2101)
        at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2193)
        ... 16 more
```

**Comment by thisisprabin** [comment]
Add the following to this file "hadoop/etc/hadoop/core-site.xml"

    <property>
      <name>fs.s3.awsAccessKeyId</name>
      <value>***</value>
    </property>
    <property>
      <name>fs.s3.awsSecretAccessKey</name>
      <value>***</value>
    </property>

sudo cp hadoop/share/hadoop/tools/lib/aws-java-sdk-1.7.4.jar  hadoop/share/hadoop/common/lib/

sudo cp hadoop/share/hadoop/tools/lib/hadoop-aws-2.7.5.jar  hadoop/share/hadoop/common/lib/

**Comment by MileanCo** [comment]
This was a problem for me on Hadoop 2.9.0, but @thisisprabin 's fix worked for me! :)

**Comment by JavadHosseini** [comment]
I did what @thisisprabin said, now I have another error.
`2021-07-13 16:45:24,411 INFO Configuration.deprecation: fs.s3a.server-side-encryption-key is deprecated. Instead, use fs.s3a.server-side-encryption.key
ls: s3a://xxxxx/: getFileStatus on s3a://xxxxx: com.amazonaws.services.s3.model.AmazonS3Exception: Forbidden (Service: Amazon S3; Status Code: 403; Error Code: 403 Forbidden; Request ID: G3VRERQTP17QZJ46; S3 Extended Request ID: hQDNxnocy+7IVcvOAZ9iP5FR6z7I1UV9tRLP2jl/OznJfVf4bLdSiKXUku8lyr+nLL6Zp21FAac=), S3 Extended Request ID: hQDNxnocy+7IVcvOAZ9iP5FR6z7I1UV9tRLP2jl/OznJfVf4bLdSiKXUku8lyr+nLL6Zp21FAac=:403 Forbidden
`
